springdoc:
  swagger-ui:
    path: /notify-docs.html
  api-docs:
    path: /notify-docs
  packages-to-scan: br.com.compasso.notifyapi.controller
kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: notify_group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      host: mongo
      port: 27017
      database: notify

    codec:
      max-in-memory-size: 2MB