kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: notify_group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      uri: mongodb://root:root@mongo:27017/
