spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: user1
    password: user1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect