springdoc:
  swagger-ui:
    path: /user-docs.html
  api-docs:
    path: /user-docs
  packages-to-scan: compasso.com.br.apiuser.controller
security:
  jwt:
    token:
      secret-key: h0cRA4Zv4hw7v4Q0kMDX730Nhr0cSDcxYqUmiogpZcrGw2wQKcuWALFrXE7jPWBP
      expire-length: 3600000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
kafka:
  topics:
    - notify-topic
  consumer:
    auto-offset-reset: latest
server:
  port: 8090