version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: fran
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: user_db
    ports:

  "5432:5432"
volumes:
  postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local